import { ListItem } from "./ListItem"


export const List = () => {
    return (
        <ul className="w-full flex flex-col">
            <ListItem title={'Title'} description={'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum accusamus dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum queso dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum accusamus dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum accusamus dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta!'}/>
            <ListItem title={'Title'} description={'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum accusamus dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum queso dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum accusamus dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum accusamus dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta!'}/>
            <ListItem title={'Title'} description={'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum accusamus dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum queso dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum accusamus dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum accusamus dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta!'}/>
            <ListItem title={'Title'} description={'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum accusamus dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum queso dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum accusamus dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa, ipsum accusamus dolor, modi quisquam illo deserunt delectus nobis, quasi quis sapiente debitis magni at omnis ex suscipit sint nulla dicta!'}/>

        </ul>
    )
}